export interface AchievementDefinition {
  id: string;
  title: string;
  description: string;
  category: 'QUESTS' | 'BOSSES' | 'STREAKS' | 'LEVELS' | 'WEALTH' | 'MASTERY';
  target: number;
  rewardXp: number;
  rewardGold: number;
  rewardTitle?: string;
  icon: string;
}

export const ACHIEVEMENTS_DATA: AchievementDefinition[] = [
  // --- QUESTS ---
  {
    id: 'quest_first_step',
    title: 'First Step to Greatness',
    description: 'Complete your very first quest.',
    category: 'QUESTS',
    target: 1,
    rewardXp: 50,
    rewardGold: 50,
    rewardTitle: 'Initiate',
    icon: 'CheckCircle',
  },
  {
    id: 'quest_ten',
    title: 'Apprentice Adventurer',
    description: 'Complete 10 quests.',
    category: 'QUESTS',
    target: 10,
    rewardXp: 150,
    rewardGold: 100,
    icon: 'Award',
  },
  {
    id: 'quest_twenty_five',
    title: 'Journeyman of Destiny',
    description: 'Complete 25 quests.',
    category: 'QUESTS',
    target: 25,
    rewardXp: 350,
    rewardGold: 200,
    rewardTitle: 'Journeyman',
    icon: 'Flame',
  },
  {
    id: 'quest_fifty',
    title: 'Master of Execution',
    description: 'Complete 50 quests across your journey.',
    category: 'QUESTS',
    target: 50,
    rewardXp: 800,
    rewardGold: 500,
    rewardTitle: 'Paragon',
    icon: 'Crown',
  },
  {
    id: 'quest_hundred',
    title: 'Living Legend',
    description: 'Complete 100 quests.',
    category: 'QUESTS',
    target: 100,
    rewardXp: 2000,
    rewardGold: 1200,
    rewardTitle: 'Grandmaster of Will',
    icon: 'Trophy',
  },

  // --- STREAKS ---
  {
    id: 'streak_3',
    title: 'Ignition',
    description: 'Maintain a 3-day active quest streak.',
    category: 'STREAKS',
    target: 3,
    rewardXp: 100,
    rewardGold: 75,
    icon: 'Zap',
  },
  {
    id: 'streak_7',
    title: 'Weekly Dominance',
    description: 'Maintain a 7-day active quest streak.',
    category: 'STREAKS',
    target: 7,
    rewardXp: 250,
    rewardGold: 150,
    rewardTitle: 'Relentless',
    icon: 'Flame',
  },
  {
    id: 'streak_14',
    title: 'Iron Fortitude',
    description: 'Maintain a 14-day quest streak without faltering.',
    category: 'STREAKS',
    target: 14,
    rewardXp: 600,
    rewardGold: 350,
    rewardTitle: 'Unbroken',
    icon: 'ShieldAlert',
  },
  {
    id: 'streak_30',
    title: 'Habit Ascendant',
    description: 'Maintain a 30-day quest streak.',
    category: 'STREAKS',
    target: 30,
    rewardXp: 1500,
    rewardGold: 1000,
    rewardTitle: 'Timeless Titan',
    icon: 'Star',
  },

  // --- BOSSES ---
  {
    id: 'boss_first_kill',
    title: 'Giant Slayer',
    description: 'Deliver the finishing blow to your first boss encounter.',
    category: 'BOSSES',
    target: 1,
    rewardXp: 200,
    rewardGold: 150,
    rewardTitle: 'Giant Slayer',
    icon: 'Swords',
  },
  {
    id: 'boss_three_kills',
    title: 'Dungeon Cleanser',
    description: 'Vanquish 3 boss encounters.',
    category: 'BOSSES',
    target: 3,
    rewardXp: 500,
    rewardGold: 300,
    rewardTitle: 'Beast Bane',
    icon: 'Skull',
  },
  {
    id: 'boss_five_kills',
    title: 'Apex Champion',
    description: 'Vanquish 5 boss encounters.',
    category: 'BOSSES',
    target: 5,
    rewardXp: 1200,
    rewardGold: 800,
    rewardTitle: 'Apex Predator',
    icon: 'Shield',
  },
  {
    id: 'boss_ten_kills',
    title: 'Mythic Conqueror',
    description: 'Vanquish 10 world boss encounters.',
    category: 'BOSSES',
    target: 10,
    rewardXp: 3000,
    rewardGold: 2000,
    rewardTitle: 'Mythic Sovereign',
    icon: 'Trophy',
  },

  // --- LEVELS ---
  {
    id: 'level_5',
    title: 'Rising Champion',
    description: 'Reach Character Level 5.',
    category: 'LEVELS',
    target: 5,
    rewardXp: 150,
    rewardGold: 100,
    icon: 'Sparkles',
  },
  {
    id: 'level_10',
    title: 'Seasoned Veteran',
    description: 'Reach Character Level 10.',
    category: 'LEVELS',
    target: 10,
    rewardXp: 400,
    rewardGold: 250,
    rewardTitle: 'Veteran',
    icon: 'Medal',
  },
  {
    id: 'level_20',
    title: 'Eminent Power',
    description: 'Reach Character Level 20.',
    category: 'LEVELS',
    target: 20,
    rewardXp: 1000,
    rewardGold: 600,
    rewardTitle: 'Ascendant',
    icon: 'Crown',
  },
  {
    id: 'level_30',
    title: 'Demigod Realm',
    description: 'Reach Character Level 30.',
    category: 'LEVELS',
    target: 30,
    rewardXp: 2500,
    rewardGold: 1500,
    rewardTitle: 'Demigod',
    icon: 'Zap',
  },

  // --- WEALTH ---
  {
    id: 'gold_250',
    title: 'Coin Collector',
    description: 'Amass 250 Gold in your treasury.',
    category: 'WEALTH',
    target: 250,
    rewardXp: 100,
    rewardGold: 50,
    icon: 'Coins',
  },
  {
    id: 'gold_1000',
    title: 'Treasury Baron',
    description: 'Amass 1,000 Gold in your treasury.',
    category: 'WEALTH',
    target: 1000,
    rewardXp: 300,
    rewardGold: 200,
    rewardTitle: 'Baron',
    icon: 'PiggyBank',
  },
  {
    id: 'gold_5000',
    title: 'Golden Mogul',
    description: 'Amass 5,000 Gold in your treasury.',
    category: 'WEALTH',
    target: 5000,
    rewardXp: 1000,
    rewardGold: 800,
    rewardTitle: 'Mogul',
    icon: 'Gem',
  },

  // --- MASTERY & FOCUS ---
  {
    id: 'skill_first_unlock',
    title: 'Talent Awakened',
    description: 'Unlock your first talent node in the Skill Tree.',
    category: 'MASTERY',
    target: 1,
    rewardXp: 100,
    rewardGold: 75,
    icon: 'Sparkles',
  },
  {
    id: 'skill_branch_specialist',
    title: 'Path Specialist',
    description: 'Unlock at least 3 skills in any single talent tree branch.',
    category: 'MASTERY',
    target: 3,
    rewardXp: 350,
    rewardGold: 200,
    rewardTitle: 'Specialist',
    icon: 'BookOpen',
  },
  {
    id: 'skill_tier4_unlock',
    title: 'Supreme Archon',
    description: 'Unlock a Tier 4 Master Talent in any branch.',
    category: 'MASTERY',
    target: 1,
    rewardXp: 1200,
    rewardGold: 800,
    rewardTitle: 'Supreme Archon',
    icon: 'Flame',
  },
  {
    id: 'party_join',
    title: 'United Fellowship',
    description: 'Join or found a Guild Party for co-op boss raids.',
    category: 'MASTERY',
    target: 1,
    rewardXp: 150,
    rewardGold: 100,
    rewardTitle: 'Guildsman',
    icon: 'Users',
  },
  {
    id: 'all_attributes_15',
    title: 'Holistic Harmony',
    description: 'Raise every single attribute (STR, INT, VIT, AGI, SPR) to at least 15.',
    category: 'MASTERY',
    target: 15,
    rewardXp: 800,
    rewardGold: 500,
    rewardTitle: 'Harmonious',
    icon: 'Compass',
  },
];
