export const DEFAULT_ITEMS = [
  {
    name: 'Novice Training Blade',
    description: 'A well-balanced wooden training sword given to aspiring heroes.',
    category: 'WEAPON',
    cost: 40,
    rarity: 'COMMON',
    icon: 'Sword',
    statType: 'STR',
    statBonus: 3,
    effectDescription: '+3 Strength bonus',
  },
  {
    name: 'Tome of Ancient Algorithms',
    description: 'An enchanted spellbook that sharpens mental clarity and analytical insight.',
    category: 'WEAPON',
    cost: 95,
    rarity: 'RARE',
    icon: 'BookOpen',
    statType: 'INT',
    statBonus: 6,
    effectDescription: '+6 Intellect bonus',
  },
  {
    name: 'Shadow Runner Daggers',
    description: 'Forged from quicksilver, these twin daggers accelerate reflex and agility.',
    category: 'WEAPON',
    cost: 160,
    rarity: 'EPIC',
    icon: 'Zap',
    statType: 'AGI',
    statBonus: 10,
    effectDescription: '+10 Agility bonus',
  },
  {
    name: 'Aegis of the Vanguard',
    description: 'A sturdy iron chestplate providing unwavering resilience against burnout.',
    category: 'ARMOR',
    cost: 120,
    rarity: 'RARE',
    icon: 'Shield',
    statType: 'VIT',
    statBonus: 8,
    effectDescription: '+8 Vitality & +25 Max HP',
  },
  {
    name: 'Celestial Archmage Robes',
    description: 'Woven with astral silk, radiates profound wisdom and spiritual equilibrium.',
    category: 'ARMOR',
    cost: 280,
    rarity: 'EPIC',
    icon: 'Sparkles',
    statType: 'SPR',
    statBonus: 14,
    effectDescription: '+14 Spirit bonus',
  },
  {
    name: 'Titanium Exosuit',
    description: 'Legendary cybernetic armor crafted for high-performing modern champions.',
    category: 'ARMOR',
    cost: 500,
    rarity: 'LEGENDARY',
    icon: 'Crown',
    statType: 'STR',
    statBonus: 20,
    effectDescription: '+20 Strength & +50 Max HP',
  },
  {
    name: 'Vitality Tonic',
    description: 'A refreshing herbal potion brewed with peppermint and mountain spring water. Restores 50 HP.',
    category: 'CONSUMABLE',
    cost: 25,
    rarity: 'COMMON',
    icon: 'FlaskConical',
    statType: 'HP',
    statBonus: 50,
    effectDescription: 'Instantly restores 50 HP',
  },
  {
    name: 'Elixir of Enlightenment',
    description: 'A shimmering gold potion granting an immediate burst of accumulated knowledge and experience.',
    category: 'CONSUMABLE',
    cost: 80,
    rarity: 'RARE',
    icon: 'Sparkle',
    statType: 'XP_BOOST',
    statBonus: 150,
    effectDescription: 'Grants instant 150 XP bonus',
  },
  {
    name: 'Order of the Phoenix Badge',
    description: 'A prestigious insignia recognizing relentless daily discipline and unwavering focus.',
    category: 'BADGE',
    cost: 150,
    rarity: 'EPIC',
    icon: 'Flame',
    statType: 'SPR',
    statBonus: 5,
    effectDescription: 'Displays legendary fiery badge on your avatar profile',
  },
];

export const STARTER_QUESTS = [
  {
    title: 'Morning Awakening & Hydration',
    description: 'Drink 500ml of clean water and stretch for 5 minutes after waking up.',
    type: 'DAILY',
    difficulty: 'EASY',
    attribute: 'VIT',
    xpReward: 30,
    goldReward: 20,
  },
  {
    title: 'Deep Work: 45-min Focus Block',
    description: 'Zero distractions, close unnecessary tabs, and push through high-priority task.',
    type: 'HABIT',
    difficulty: 'MEDIUM',
    attribute: 'INT',
    xpReward: 60,
    goldReward: 40,
  },
  {
    title: 'Strength & Conditioning Training',
    description: 'Complete 30 minutes of gym workout, bodyweight training, or brisk cardio.',
    type: 'DAILY',
    difficulty: 'HARD',
    attribute: 'STR',
    xpReward: 120,
    goldReward: 80,
  },
  {
    title: 'Mindfulness & Meditation',
    description: '10 minutes of calm breathing, stillness, or evening gratitude journaling.',
    type: 'DAILY',
    difficulty: 'EASY',
    attribute: 'SPR',
    xpReward: 30,
    goldReward: 20,
  },
  {
    title: 'Inbox Zero & Rapid Errands',
    description: 'Clear critical emails and organize tomorrow’s plan of attack.',
    type: 'TODO',
    difficulty: 'EASY',
    attribute: 'AGI',
    xpReward: 30,
    goldReward: 20,
  },
  {
    title: 'Slay the Procrastination Titan',
    description: 'Tackle the one dreaded project you have been putting off for days.',
    type: 'BOSS',
    difficulty: 'EPIC',
    attribute: 'INT',
    xpReward: 250,
    goldReward: 180,
  },
];

export const DEFAULT_BOSS = {
  name: 'Chronos the Procrastinator',
  title: 'Ancient Devourer of Hours',
  description: 'A colossal shadow drake that feeds on delayed ambitions and forgotten to-dos. Complete quests to deplete its life force!',
  maxHp: 2000,
  currentHp: 1650,
  avatar: 'dragon',
  weakness: 'INT',
  rewardGold: 350,
  rewardXp: 500,
  isActive: true,
};
